// src/reducers/saveMigration.js - Save data migration & persistence filtering
// Separated from saveReducer.js to avoid circular dependencies.
//
// P0-4: Migration mechanism for version-incompatible saves
// P0-5: State filtering for persisted saves (exclude runtime UI fields)

import { resolveNpcId } from '../data/registry/npcRegistry.js';
import { migrateInventory } from '../data/registry/itemRegistry.js';
import { TRANSIENT_STATE_KEYS } from '../state/transientKeys.js';
import { initialState } from '../state/initialState.js';

/**
 * Save version — bump when save format changes.
 * Must match SAVE_VERSION in saveReducer.js.
 */
export const SAVE_VERSION = '1.2.0';

// State fields excluded from persistence even though they are present in
// initialState. Keeping this list beside toPersistedState makes the save and
// load boundaries share one definition instead of maintaining parallel
// whitelists in SaveManager and loopSlice.
const UI_STATE_KEYS = [
  'narrative',
  'transition',
  'pendingNpc',
  'pendingChoice',
  'pendingGamble',
  'pendingEvent',
  'pendingDeath',
];
const TRANSIENT_LOOP_KEYS = ['_prevRunStateForSanLegacy'];
var _persistedStateKeysCache = null;

function getPersistenceExclusionSet() {
  return new Set([...UI_STATE_KEYS, ...TRANSIENT_STATE_KEYS, ...TRANSIENT_LOOP_KEYS]);
}

/**
 * Return the authoritative list of state keys that may be written to a save.
 * Persisted fields must first be registered in initialState; this prevents a
 * newly added arbitrary property from silently becoming part of the format.
 */
export function getPersistedStateKeys(GD) {
  if (!_persistedStateKeysCache) {
    const template = initialState(GD || {});
    const excluded = getPersistenceExclusionSet();
    _persistedStateKeysCache = Object.keys(template).filter(function (key) {
      return !excluded.has(key);
    });
  }
  return _persistedStateKeysCache.slice();
}

/**
 * Loading accepts the persisted contract plus short-lived migration markers
 * generated by migrateSaveData itself.
 */
export function getLoadableStateKeys(GD) {
  return getPersistedStateKeys(GD).concat(['_difficultyMigrated']);
}

/**
 * Minimal extended state defaults (subset of ensureExtendedState).
 * Used during migration when ensureExtendedState is not available
 * (e.g., in Node.js test environments).
 *
 * This is intentionally kept lightweight — the full ensureExtendedState
 * from extendedEventsLoader.js is still called in CONTINUE_GAME as a
 * second safety net.
 */
export function ensureMinimalExtendedState(state) {
  if (!state.previousRunSummary) state.previousRunSummary = null;
  if (!state.previousDeathsByArea) state.previousDeathsByArea = {};
  if (!state.previousEndings) state.previousEndings = [];
  if (!state.endingHistory) state.endingHistory = [];
  if (!state.loopEchoFlags) state.loopEchoFlags = [];
  if (!state.worldCorrectionFlags) state.worldCorrectionFlags = [];
  if (!state.playerTraces) state.playerTraces = [];
  if (!state.eventCooldowns) state.eventCooldowns = {};
  if (!state.categoryCountsToday) state.categoryCountsToday = {};
  if (!state.categoryCountsRun) state.categoryCountsRun = {};
  if (!state.abnormalStreak) state.abnormalStreak = 0;
  if (!state.runTriggeredExtendedEvents) state.runTriggeredExtendedEvents = [];
  if (!state.everTriggeredEvents) state.everTriggeredEvents = [];
  if (!state.pendingFollowupEvents) state.pendingFollowupEvents = [];
  if (!state.unlockedAreas) state.unlockedAreas = [];
  if (!state.unlockedEndingConditions) state.unlockedEndingConditions = [];
  if (!state.endingEchoes) state.endingEchoes = [];
  if (!state.lastDeathHint) state.lastDeathHint = null;
  if (!state.deathContext) state.deathContext = null;
  if (!state.lastDeathMode) state.lastDeathMode = null;
  if (!state.previousDeathContext) state.previousDeathContext = null;
  if (!state.prologue) state.prologue = null;
  if (!state.fearTuning) state.fearTuning = null;
  if (!state.sanityCollapseCount) state.sanityCollapseCount = 0;
  return state;
}

/**
 * Build a save meta object from game state.
 * Used when migrating old saves that lack a meta field.
 */
export function buildSaveMeta(state) {
  return {
    day: state.day || 1,
    area: state.currentArea || '',
    loopCount: state.loopCount || 0,
    san: state.san || 0,
    hp: state.hp || 0,
  };
}

/**
 * Migrate save data from any older version to current version.
 *
 * P0-4: Instead of deleting incompatible saves, we attempt to migrate them.
 * Returns the migrated save data, or null if the save is unrecoverable.
 *
 * @param {object} data - raw save data from localStorage
 * @param {string} slotId - the slot ID
 * @returns {object|null} migrated save data, or null if unrecoverable
 */
export function migrateSaveData(data, slotId) {
  if (!data) return null;

  // Handle both wrapped ({ version, state }) and unwrapped (raw state) formats
  let state = data.state || data;
  if (!state || typeof state !== 'object') return null;

  // Check for obviously corrupt data (not an object, or missing critical fields)
  // We're lenient: only reject if there's no way to reconstruct
  if (typeof state.day !== 'number' && typeof state.screen !== 'string') {
    return null;
  }

  // Apply minimal extended state defaults for backward compatibility
  state = ensureMinimalExtendedState(state);

  // Migrate flat behavior tracking counters into behaviorTracking object (v1.2.0)
  if (!state.behaviorTracking) {
    const BT_KEYS = [
      'direct_kill_count',
      'cannibalism_count',
      'clean_kill_pattern',
      'npc_deaths_by_manipulation',
      'cult_leader_score',
      'self_harm_ritual_count',
      'fusion_accepted_count',
      'possession_accepted_count',
      'forbidden_intimacy_flags',
      'sacred_desecration_count',
      'same_npc_harm_max',
      '_npc_harm_tally',
      'npc_as_resource_count',
      'betrayed_high_trust_npcs',
      'self_sacrifice_for_power',
      'fusion_and_self_harm_total',
      'harbor_visits',
      'sea_acceptance_flags',
      'sleep_streak',
      'work_only_days',
      'safehouse_stay_days',
      'move_only_days',
      'record_only_days',
      'low_intervention_count',
      'work_count',
      'hoarded_money_max',
      'hoarded_food_max',
      'archive_consumed_count',
      'prophecy_spread_count',
      'redeemed_npcs',
      'thirteenth_bell_obsession',
      'meta_boundary_breaks',
      'final_choice_refused_count',
      'save_delete_attempts',
      'loop_exploit_score',
      'loop_break_attempts',
    ];
    const bt = {};
    for (const key of BT_KEYS) {
      if (state[key] !== undefined) {
        bt[key] = state[key];
        delete state[key];
      }
    }
    state.behaviorTracking = bt;
  }

  // Migrate NPC keys from Chinese name to stable id (v1.3.0)
  // npcTrust, npcStates, npcRelations are keyed by NPC identifier.
  // Old saves use Chinese names; new system uses stable ids (e.g. martha_grey).
  if (typeof resolveNpcId === 'function') {
    const NPC_KEYED_FIELDS = [
      'npcTrust',
      'npcStates',
      'npcRelations',
      '_npcTrustLocked',
      '_npcHarmTally',
    ];
    for (const field of NPC_KEYED_FIELDS) {
      const obj = state[field];
      if (obj && typeof obj === 'object' && !Array.isArray(obj)) {
        const migrated = {};
        let changed = false;
        for (const [key, val] of Object.entries(obj)) {
          const newKey = resolveNpcId(key);
          if (newKey !== key) changed = true;
          migrated[newKey] = val;
        }
        if (changed) state[field] = migrated;
      }
    }
    // Also migrate npc data inside behaviorTracking
    if (state.behaviorTracking && typeof state.behaviorTracking === 'object') {
      const bt = state.behaviorTracking;
      if (bt._npc_harm_tally && typeof bt._npc_harm_tally === 'object') {
        const migrated = {};
        for (const [key, val] of Object.entries(bt._npc_harm_tally)) {
          migrated[resolveNpcId(key)] = val;
        }
        bt._npc_harm_tally = migrated;
      }
    }
  }

  // Migrate inventory items from Chinese name to stable id (v1.3.0)
  if (typeof migrateInventory === 'function' && Array.isArray(state.inventory)) {
    state.inventory = migrateInventory(state.inventory);
  }

  // Difficulty migration: old saves had levels 1-21, new system is 1-13
  if (typeof state.difficultyLevel === 'number' && state.difficultyLevel > 13) {
    state.difficultyLevel = 13;
    state._difficultyMigrated = true;
  }

  // Build the migrated save object
  return {
    version: SAVE_VERSION,
    timestamp: data.timestamp || Date.now(),
    slotId: data.slotId || slotId,
    meta: data.meta || buildSaveMeta(state),
    state,
  };
}

/**
 * Filter state for persistence: remove runtime UI fields that shouldn't be saved.
 *
 * P0-5: Prevents save bloat from narrative array and avoids restoring
 * half-open UI states (pending choices, transitions, etc.).
 *
 * @param {object} state - full game state
 * @returns {object} filtered state safe for persistence
 */
export function toPersistedState(state) {
  const allowedKeys = new Set(getPersistedStateKeys(state?._GD));

  const persisted = {};
  for (const [k, v] of Object.entries(state)) {
    if (allowedKeys.has(k)) persisted[k] = v;
  }

  // Cap eventLog (same rationale as narrative)
  if (persisted.eventLog && persisted.eventLog.length > 200) {
    persisted.eventLog = persisted.eventLog.slice(-200);
  }

  return persisted;
}
