// src/state/initialState.js — 游戏初始状态定义（从 app.jsx 提取）

const initialState=()=>{
  const base={screen:'title',day:1,ap:12,maxAp:12,
  stats:{STR:50,CON:55,DEX:55,APP:50,POW:60,INT:65,SIZ:60,EDU:70},
  hp:11,maxHp:11,san:60,maxSan:60,luck:50,mp:12,
  currentArea:'town_center',visitedAreas:['town_center'],
  inventory:(GD.systems?.player?.starting_items?.starting_items||[]).map(item=>{
    const idMap={'手电筒':'flashlight','笔记本和笔':'notebook','急救包':'first_aid_kit','怀表':'pocket_watch'};
    return {id:idMap[item.name]||item.name,name:item.name,uses:item.uses};
  }),
  clues:[],skills:{},npcTrust:{},npcStates:{},
  sealState:'intact',weather:'阴天',
  triggeredEvents:[],triggeredSilentEvents:[],longTermEffects:[],madnessActive:null,
  objectives:[],completedChains:[],
  difficulty:'normal',
  narrative:[],eventLog:[],pendingEvent:null,pendingNpc:null,pendingGamble:null,pendingChoice:null,ending:null,transition:null,
  safehouseCorruption:0,currentSafehouse:'main',
  harborRiskReduction:0,
  tempSkillBonus:null,
  stats_run:{deaths:0,runs:1,checks_passed:0,checks_failed:0,days_best:0,max_san_loss_single:0,total_san_loss:0,deepest_area_danger:0},
  ch1IntroComplete:false,
  food:3,maxFood:5,lightLevel:2,starvationDays:0,
  infection:0,maxInfection:10,fatigue:0,maxFatigue:10,
  loopCount:0,pollution:0,
  areaNameCache:{},
  retainedKnowledge:[],
  lastVisitedDates:{},
  lastDeathType:null,
  mythosLevel:0,currentChapter:'chapter_1',
  humanityScore:50,discoveredConclusions:[],
  accessibilityOptions:{visual_distortion:true,flicker_control:true,pseudo_error_style:'immersive'},
  activeBlessings:[],
  archetype:null,
  runMemory:[],
  audioMuted:false,
  tutorialSeen:{},
  guideSeen:false,
  prologue: null,
  fearTuning: null,
  behaviorTracking:{
    direct_kill_count:0, cannibalism_count:0, clean_kill_pattern:0,
    npc_deaths_by_manipulation:0, cult_leader_score:0,
    self_harm_ritual_count:0, fusion_accepted_count:0, possession_accepted_count:0,
    forbidden_intimacy_flags:0, sacred_desecration_count:0, same_npc_harm_max:0,
    _npc_harm_tally:{}, npc_as_resource_count:0, betrayed_high_trust_npcs:0,
    self_sacrifice_for_power:0, fusion_and_self_harm_total:0, harbor_visits:0,
    sea_acceptance_flags:0, sleep_streak:0, work_only_days:0, safehouse_stay_days:0,
    move_only_days:0, record_only_days:0, low_intervention_count:0, work_count:0,
    hoarded_money_max:0, hoarded_food_max:0, archive_consumed_count:0,
    prophecy_spread_count:0, redeemed_npcs:0, thirteenth_bell_obsession:0,
    meta_boundary_breaks:0, final_choice_refused_count:0, save_delete_attempts:0,
    loop_exploit_score:0, loop_break_attempts:0,
  },
  money:0,
  _dayActions:[],
  _dayStartArea:null,
  _lastAreaBeforeRest:null,
  _dayStartSan:null,
  _dayStartHp:null,
  _dayStartClueCount:null,
  _dailyTrustGains:{},
  _visualPollution:50,
  _actionHistory:[],
  _todayEventTypes:[],
  _recentEventIds:[],
  eventCooldowns:{}
  };
  return ensureExtendedState(base);
};
