import os, re, sys

src_dir = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), 'src')
skip_dirs = {'vendor', 'node_modules', '.git'}

known_funcs = {
    'hasClueId': 'utils/clueNameMap.js', 'resolveClueName': 'utils/clueNameMap.js',
    'applyEffects': 'reducers/effectReducer.js', 'applyLegacyEffects': 'reducers/effectReducer.js',
    'clamp': 'reducers/utils.js', 'pick': 'reducers/utils.js', 'rand': 'reducers/utils.js',
    'makeRand': 'reducers/utils.js', 'rollDice': 'reducers/utils.js', 'd100': 'reducers/utils.js',
    'd3': 'reducers/utils.js', 'applySanLoss': 'reducers/utils.js', 'getCurrentSanStage': 'reducers/utils.js',
    'getPhase': 'engine/WorldTimeSystem.js', 'getAreaInfo': 'engine/WorldTimeSystem.js',
    'getSealState': 'engine/WorldTimeSystem.js', 'getSealStateId': 'engine/WorldTimeSystem.js',
    'getWeather': 'engine/WorldTimeSystem.js',
    'getSanStage': 'reducers/sanReducer.js', 'getSanStageFromGD': 'reducers/sanReducer.js',
    'processSanLoss': 'reducers/sanReducer.js', 'rollMadness': 'reducers/sanReducer.js',
    'getSafehouseStage': 'reducers/miscReducer.js', 'processSafehouseNight': 'reducers/miscReducer.js',
    'getLightLevelEffects': 'reducers/miscReducer.js', 'applyLightTextCorruption': 'reducers/miscReducer.js',
    'getItemDef': 'reducers/miscReducer.js', 'useItemByDef': 'reducers/miscReducer.js',
    'checkEnding': 'reducers/endingReducer.js',
    'checkNPCCorruption': 'reducers/npcReducer.js', 'applyNPCCorruption': 'reducers/npcReducer.js',
    'setCorruptionFlag': 'reducers/npcReducer.js',
    'getChapterForDay': 'reducers/chapterReducer.js', 'getMotifFlavorText': 'reducers/chapterReducer.js',
    'checkChapterTransition': 'reducers/chapterReducer.js', 'getMonsterManifestation': 'reducers/chapterReducer.js',
    'checkConclusions': 'reducers/conclusionReducer.js', 'checkFalseInterpretations': 'reducers/conclusionReducer.js',
    'genObjectives': 'reducers/objectiveReducer.js', 'checkObjCompletion': 'reducers/objectiveReducer.js',
    'getForcedProgressGuard': 'reducers/objectiveReducer.js', 'executeForcedProgressGuard': 'reducers/objectiveReducer.js',
    'resolveDeath': 'reducers/deathSystem.js',
    'initLoopState': 'reducers/loopReducer.js', 'buildPreviousRunSummary': 'reducers/extendedEvents.js',
    'applyExtendedEffect': 'reducers/extendedEvents.js',
    'selectEventV2': 'reducers/extendedEvents.js', 'getEligibleEvents': 'reducers/extendedEvents.js',
    'chooseWeightedEvent': 'reducers/extendedEvents.js', 'commitSelectedEvent': 'reducers/extendedEvents.js',
    'getEventWeight': 'reducers/extendedEvents.js', 'checkTriggerExtended': 'reducers/extendedEvents.js',
    'resetDailyCategoryCounts': 'reducers/extendedEvents.js',
    'checkTrigger': 'reducers/eventReducer.js', 'doSkillCheck': 'reducers/eventReducer.js',
    'getGambleOptions': 'reducers/eventReducer.js', 'selectEvent': 'reducers/eventReducer.js',
    'checkChapterMilestone': 'engine/EventEngine.js', 'createMilestoneEvent': 'engine/EventEngine.js',
    'getDistortionVariant': 'engine/EventEngine.js', 'checkForcedNarrativeHook': 'engine/EventEngine.js',
    'addRunMemory': 'utils/appHelpers.js', 'modHumanity': 'utils/appHelpers.js',
    'getNpcTrust': 'utils/appHelpers.js', 'setNpcTrust': 'utils/appHelpers.js',
    'getNpcState': 'utils/appHelpers.js', 'setNpcState': 'utils/appHelpers.js',
    'applyDeathResolution': 'utils/appHelpers.js', 'buildDeathRecap': 'utils/appHelpers.js',
    'applyBlessing': 'utils/appHelpers.js', 'getAvailableSafehouses': 'utils/appHelpers.js',
    'checkWrongInference': 'utils/appHelpers.js', 'checkKnowledgeEarned': 'utils/appHelpers.js',
    'checkBreakWallEvent': 'utils/appHelpers.js', 'checkSilentEvent': 'utils/appHelpers.js',
    'narrDailySummary': 'utils/appHelpers.js', 'narrApInsufficient': 'utils/appHelpers.js',
    'getDisplayedAp': 'utils/appHelpers.js', 'getUICorruptionLayer': 'utils/appHelpers.js',
    'trackDailyBehaviorPatterns': 'utils/appHelpers.js', 'preloadEndingCGs': 'utils/appHelpers.js',
    'checkChainCompletion': 'utils/gameHelpers.js', 'isAreaUnlocked': 'utils/gameHelpers.js',
    'getAreaDisplayName': 'utils/gameHelpers.js', 'initSkills': 'utils/gameHelpers.js', 'getNpcsHere': 'utils/gameHelpers.js',
    'handleNpcMemoryTier': 'utils/npcMemory.js', 'checkTrustGate': 'utils/trustGates.js',
    'computeNpcFeedback': 'systems/npcFeedback.js', 'getTrustTierInfo': 'systems/npcFeedback.js',
    'getNpcDialogueVariant': 'systems/npcDialogue.js', 'getNpcFatigueEffect': 'systems/npcDialogue.js',
    'NPC_CORRUPTION_LINES': 'systems/npcDialogue.js',
    'getFearNpcLine': 'systems/fearLens.js', 'applyFearLens': 'systems/fearLens.js',
    'getFearEventWeightModifier': 'systems/fearLens.js',
    'adjustSanLossForFirstLoop': 'systems/firstLoopBalance.js', 'shouldBlockLethalEvent': 'systems/firstLoopBalance.js',
    'getTrackedText': 'systems/textVariants.js', 'createSeenTextMap': 'systems/textVariants.js',
    'applyMythosAliases': 'systems/textVariants.js', 'maybeInjectPhantomNarrative': 'systems/textVariants.js',
    'maybeInjectPhantomLog': 'systems/textVariants.js',
    'applyResourceTextCorruption': 'systems/resourceNarrative.js', 'getResourceNarrative': 'systems/resourceNarrative.js',
    'getSafehouseVisualStage': 'systems/resourceNarrative.js', 'getSafehousePollutionEvent': 'systems/resourceNarrative.js',
    'processDailyResources': 'systems/resourceNarrative.js',
    'getAreaCorruptionNarrative': 'systems/worldDecay.js', 'getDayCriticalEvent': 'systems/worldDecay.js',
    'getWorldDecayNarrative': 'systems/worldDecay.js', 'getHarborDeepOneWhisper': 'systems/worldDecay.js',
    'calculateDailyCorruption': 'systems/worldDecay.js', 'updateAreaCorruption': 'systems/worldDecay.js',
    'applyMetaCorruption': 'systems/metaCorruption.js',
    'applyTextHallucination': 'engine/PollutionManager.js', 'maybeGetFakeMessage': 'engine/PollutionManager.js',
    'maybeInsertFalseMemory': 
